# Generated by Django 4.2.1 on 2023-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='foto',
            field=models.ImageField(default='default_farm.jpg', null=True, upload_to='farm_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='default_profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
