# Generated by Django 4.1.3 on 2023-05-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='farm',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='farm',
            name='country',
            field=models.CharField(default='Latvija', max_length=200),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
