# Generated by Django 4.1.3 on 2023-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_farm_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
