# Generated by Django 4.1.3 on 2023-06-03 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_farm_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{8}$')]),
        ),
    ]
