# Generated by Django 4.1.3 on 2023-06-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_client_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='default_profile.jpg', null=True, upload_to=''),
        ),
    ]
