# Generated by Django 4.1.3 on 2023-06-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='foto',
            field=models.ImageField(default='default_farm.jpg', null=True, upload_to=''),
        ),
    ]
