# Generated by Django 4.1.3 on 2022-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saimnieciba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nosaukums', models.CharField(max_length=200)),
                ('apraksts', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
                ('lokacija', models.CharField(max_length=200)),
            ],
        ),
    ]
