# Generated by Django 4.1.3 on 2023-04-28 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('s_nosaukums', models.CharField(max_length=200)),
                ('s_apraksts', models.TextField()),
                ('s_foto', models.ImageField(default='defaultx.jpg', null=True, upload_to='')),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('talrunis', models.CharField(max_length=8)),
                ('lokacija', models.CharField(max_length=200)),
                ('s_datums', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saimniecibas_profile',
            },
        ),
    ]
