# Generated by Django 4.1.3 on 2022-11-07 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('saimniecibas', '0005_alter_saimnieciba_s_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saimnieciba',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
