# Generated by Django 4.1.3 on 2022-12-03 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produkcija', '0003_remove_produkts_saimnieciba_produkts_p_datums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saimniecibas', '0006_alter_saimnieciba_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('s_nosaukums', models.CharField(max_length=200)),
                ('s_apraksts', models.TextField()),
                ('s_foto', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='')),
                ('epasts', models.EmailField(blank=True, max_length=500, null=True)),
                ('talrunis', models.CharField(max_length=8)),
                ('lokacija', models.CharField(max_length=200)),
                ('s_datums', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Saimnieciba',
        ),
    ]
