# Generated by Django 4.1.3 on 2022-12-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saimniecibas', '0007_profile_delete_saimnieciba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='epasts',
            new_name='email',
        ),
    ]
