# Generated by Django 4.1.3 on 2022-11-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saimniecibas', '0008_saimnieciba_lietotajs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saimnieciba',
            old_name='lietotajs',
            new_name='user',
        ),
    ]
