# Generated by Django 4.1.3 on 2022-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saimniecibas', '0008_rename_epasts_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
