# Generated by Django 4.1.3 on 2022-11-20 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saimniecibas', '0009_rename_lietotajs_saimnieciba_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saimnieciba',
            old_name='user',
            new_name='lietotajs',
        ),
    ]
