# Generated by Django 4.1.3 on 2022-12-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saimniecibas', '0009_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='s_foto',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
