# Generated by Django 4.1.3 on 2023-03-27 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saimniecibas', '0018_alter_profile_s_foto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='saimniecibas_profile',
        ),
    ]
