# Generated by Django 4.1.3 on 2023-04-28 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saimniecibas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('p_nosaukums', models.CharField(max_length=200)),
                ('p_apraksts', models.TextField()),
                ('p_foto', models.ImageField(null=True, upload_to='')),
                ('cena', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cenas_mervieniba', models.CharField(choices=[('kg', 'kilogrami'), ('g', 'grami'), ('l', 'litri'), ('ml', 'mililitri'), ('gab', 'gabalā')], max_length=100)),
                ('p_datums', models.DateTimeField(default=django.utils.timezone.now)),
                ('saimnieciba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saimniecibas.profile')),
            ],
        ),
    ]
