# Generated by Django 4.1.3 on 2022-11-07 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('produkcija', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkts',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
