# Generated by Django 4.1.3 on 2022-12-03 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produkcija', '0002_alter_produkts_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkts',
            name='saimnieciba',
        ),
        migrations.AddField(
            model_name='produkts',
            name='p_datums',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
