# Generated by Django 4.1.3 on 2022-12-03 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saimniecibas', '0007_profile_delete_saimnieciba'),
        ('produkcija', '0004_produkts_saimieciba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkts',
            name='saimieciba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saimniecibas.profile'),
        ),
    ]
