# Generated by Django 4.1.3 on 2022-12-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcija', '0006_rename_produkts_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='saimieciba',
            new_name='saimnieciba',
        ),
        migrations.AlterField(
            model_name='product',
            name='cenas_mervieniba',
            field=models.CharField(choices=[('kg', 'kilogrami'), ('g', 'grami'), ('l', 'litri'), ('ml', 'mililitri'), ('gab', 'gabalā')], max_length=100),
        ),
    ]
