# Generated by Django 4.1.3 on 2023-02-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkcija', '0007_rename_saimieciba_product_saimnieciba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='p_foto',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
